### ISSUE TITLE
Crashes Sanity Studio

### ISSUE THREAD

**Issue by bjornwang** [ahmdigital/content-model-graph#33]
This looks like a fantastic plugin!

Sadly, it immediately crashes Sanity Studio for me:

Stack trace:
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (/static/js/vendor.bundle.js:23203:13)
    at useState (/static/js/vendor.bundle.js:5054:21)
    at ContentModelGraph (/static/js/app.bundle.js:245329:39)
    at ProxyComponent.hotComponentRender (/static/js/app.bundle.js:106831:16)
    at ProxyComponent.proxiedRender (/static/js/app.bundle.js:106848:36)
    at finishClassComponent (/static/js/vendor.bundle.js:25495:31)
    at updateClassComponent (/static/js/vendor.bundle.js:25448:24)
    at beginWork$1 (/static/js/vendor.bundle.js:27211:16)
    at HTMLUnknownElement.callCallback (/static/js/vendor.bundle.js:7361:14)
    at Object.invokeGuardedCallbackDev (/static/js/vendor.bundle.js:7410:16)
Component stack:
    in ContentModelGraph
    in component (created by RenderTool)
    in RenderTool (created by SchemaErrorReporter)
    in RouteScope (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in div (created by SchemaErrorReporter)
    in SchemaErrorReporter (created by DefaultLayout)
    in DefaultLayout (created by withRouter(DefaultLayout))
    in withRouter(DefaultLayout) (created by DefaultLayoutContainer)
    in RouterProvider (created by DefaultLayoutContainer)
    in LoginWrapper (created by DefaultLayoutContainer)
    in DefaultLayoutContainer (created by SanityRoot)
    in div (created by SanityRoot)
    in SanityRoot
    in AppContainer

Any hints as to how I can overcome this?

**Comment by bjornwang** [comment]
Solved by upgrading to the Sanity version.
